[features]
seeds = false
skip-lint = false
[programs.devnet]
clockwork_test = "CtoKnpCU5pDfKiXsAD3mz73BThpZC9fzxCKkBsActXuf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ascespool/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
